### ISSUE TITLE
一个关于计算mAP的问题

### ISSUE THREAD

**Issue by klinic** [MCG-NJU/MultiSports#11]
主办方，您们好。能不能用你们的evaluate的代码测试val数据集（即：multisports_GT.pkl中test下的所有视频）的frame mAP， video mAP。因为我们模型跑出来的mAP结果和用你们提供的代码测的mAP有些差距。 : )

Translate to English:
I want to know if i can use your evaluate.py to caculate validation dataset's frame_mAP,video_mAP? My model caculate the frame_mAP is different from the result of your evaluate.py.
Thanks!!!

**Comment by pokameng** [comment]
@yixuanli98 
I want to know if i can use your evaluate.py to caculate validation dataset's frame_mAP,video_mAP? My model caculate the frame_mAP is different from the result of your evaluate.py.
Thanks!!!

**Comment by yixuanli98** [comment]
> 主办方，您们好。能不能用你们的evaluate的代码测试val数据集（即：multisports_GT.pkl中test下的所有视频）的frame mAP， video mAP。因为我们模型跑出来的mAP结果和用你们提供的代码测的mAP有些差距。 : )
> 
> Translate to English:
> I want to know if i can use your evaluate.py to caculate validation dataset's frame_mAP,video_mAP? My model caculate the frame_mAP is different from the result of your evaluate.py.
> Thanks!!!

**Comment by yixuanli98** [comment]
Sorry for late reply. Of course you can. The 'evaluate.py' is exactly the evaluate program in the codalab.

**Comment by pokameng** [comment]
OK，thanks！！！



---原始邮件---
发件人: "Yixuan ***@***.***&gt;
发送时间: 2021年9月12日(周日) 下午3:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MCG-NJU/MultiSports] 一个关于计算mAP的问题 (#11)




 
Sorry for late reply. Of course you can. The 'evaluate.py' is exactly the evaluate program in the codalab.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pokameng** [comment]
So the groundtruth for val is&nbsp; the train_GT.pkl，right？



---原始邮件---
发件人: "Yixuan ***@***.***&gt;
发送时间: 2021年9月12日(周日) 下午3:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MCG-NJU/MultiSports] 一个关于计算mAP的问题 (#11)




 
Sorry for late reply. Of course you can. The 'evaluate.py' is exactly the evaluate program in the codalab.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pokameng** [comment]
Hello! I am sorry to bother you again.&nbsp;
My&nbsp; team member submit the pkl used different teamname , does it will affect the final results？





---原始邮件---
发件人: "Yixuan ***@***.***&gt;
发送时间: 2021年9月12日(周日) 下午3:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MCG-NJU/MultiSports] 一个关于计算mAP的问题 (#11)




 
Sorry for late reply. Of course you can. The 'evaluate.py' is exactly the evaluate program in the codalab.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yixuanli98** [comment]
You could send the ids of your team members to me.

**Comment by yixuanli98** [comment]
Through E-mail : liyixxxuan@gmail.com
